Add missing dependency
Resolves `java.lang.NoClassDefFoundError:
com/fasterxml/jackson/core/util/JacksonFeature` when updating jackson version
to 2.12.0